# Generated by Django 5.2.13 on 2026-05-02 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_items', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_details', models.TextField()),
                ('valid_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_batteries', to='inventory.stockitem')),
                ('charger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_chargers', to='inventory.stockitem')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='leads.lead')),
                ('scooter_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.scootermodel')),
            ],
        ),
    ]
