# Generated by Django 5.2.13 on 2026-09-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_rejection_reason_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
