# Generated by Django 5.2.13 on 2026-09-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_scootermodel_deleted_at_scootermodel_is_deleted_and_more'),
        ('leads', '0003_lead_deleted_at_lead_is_deleted_quote_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('custom_item_name', models.CharField(blank=True, help_text='Used when item is not in DB inventory', max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='leads.lead')),
                ('scooter_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_requirements', to='inventory.scootermodel')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_requirements', to='inventory.stockitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
