# Generated by Django 5.2.13 on 2026-04-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('range_km', models.IntegerField()),
                ('watts', models.IntegerField()),
                ('charging_time', models.FloatField()),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('battery_lithium_60w_range', models.IntegerField(blank=True, help_text='Range with 60W Lithium Battery', null=True)),
                ('battery_lithium_72w_range', models.IntegerField(blank=True, help_text='Range with 72W Lithium Battery', null=True)),
                ('battery_lead_60w_range', models.IntegerField(blank=True, help_text='Range with 60W Lead Battery', null=True)),
                ('battery_lead_72w_range', models.IntegerField(blank=True, help_text='Range with 72W Lead Battery', null=True)),
                ('misc', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('SCOOTER', 'Electric Scooter'), ('BATTERY', 'Battery'), ('CHARGER', 'Battery Charger'), ('SPARE', 'Spare Part')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('DEFECTIVE', 'Defective')], default='AVAILABLE', max_length=20)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('supplier_details', models.TextField(blank=True, null=True)),
                ('battery_type', models.CharField(blank=True, choices=[('LITHIUM', 'Lithium Battery'), ('LEAD', 'Lead Battery')], max_length=20, null=True)),
                ('wattage', models.CharField(blank=True, choices=[('60W', '60 Watt'), ('72W', '72 Watt')], max_length=20, null=True)),
                ('misc', models.JSONField(blank=True, default=dict, null=True)),
                ('scooter_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.scootermodel')),
            ],
        ),
    ]
