# Generated by Django 5.2.13 on 2026-10-04 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('battery_type', models.CharField(choices=[('LITHIUM', 'Lithium Ion / LFP'), ('LEAD_ACID', 'Lead Acid'), ('GRAPHENE', 'Graphene')], default='LITHIUM', max_length=20)),
                ('voltage', models.CharField(choices=[('48V', '48V'), ('60V', '60V'), ('72V', '72V')], default='60V', max_length=20)),
                ('capacity_ah', models.CharField(blank=True, default='30Ah', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('price_with_scooter', models.DecimalField(decimal_places=2, default=0.0, help_text='Bundled price when purchased alongside a scooter', max_digits=12)),
                ('price_without_scooter', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard retail price when purchased independently', max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('DEFECTIVE', 'Defective')], default='AVAILABLE', max_length=20)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('supplier_details', models.TextField(blank=True, null=True)),
                ('misc', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('charger_type', models.CharField(default='Standard Fast Charger', max_length=50)),
                ('voltage', models.CharField(choices=[('48V', '48V'), ('60V', '60V'), ('72V', '72V')], default='60V', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('price_with_scooter', models.DecimalField(decimal_places=2, default=0.0, help_text='Price with scooter (usually 0.00 for 1st bundled charger)', max_digits=12)),
                ('price_without_scooter', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard retail price when bought standalone', max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('DEFECTIVE', 'Defective')], default='AVAILABLE', max_length=20)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('supplier_details', models.TextField(blank=True, null=True)),
                ('misc', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('watts', models.IntegerField(default=1200, help_text='Motor power in watts')),
                ('charging_time', models.FloatField(default=4.0, help_text='Charging time in hours')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost Price', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base Selling Price', max_digits=12)),
                ('battery_lithium_60w_range', models.IntegerField(default=85, help_text='Range with 60V Lithium Battery (km)')),
                ('battery_lithium_72w_range', models.IntegerField(default=115, help_text='Range with 72V Lithium Battery (km)')),
                ('battery_lead_60w_range', models.IntegerField(default=55, help_text='Range with 60V Lead Acid Battery (km)')),
                ('battery_lead_72w_range', models.IntegerField(default=70, help_text='Range with 72V Lead Acid Battery (km)')),
                ('default_range_km', models.IntegerField(default=80, help_text='Default/Nominal Range (km)')),
                ('description', models.TextField(blank=True, null=True)),
                ('misc', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, default='General Spare', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of Stock')], default='AVAILABLE', max_length=20)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('supplier_details', models.TextField(blank=True, null=True)),
                ('misc', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('chassis_number', models.CharField(max_length=100, unique=True)),
                ('motor_number', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='Standard', max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('DEFECTIVE', 'Defective')], default='AVAILABLE', max_length=20)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('supplier_details', models.TextField(blank=True, null=True)),
                ('misc', models.JSONField(blank=True, default=dict, null=True)),
                ('scooter_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scooters', to='inventory.scootermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
