# Generated by Django 5.2.13 on 2026-05-02 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptask',
            name='external_assignee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shoptask',
            name='task_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='stage_type',
            field=models.CharField(choices=[('START', 'Start'), ('MIDDLE', 'Ongoing'), ('END', 'End')], default='MIDDLE', max_length=10),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='next_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='prefix',
            field=models.CharField(default='TASK', max_length=10),
        ),
        migrations.AlterField(
            model_name='shoptask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('from_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='tasks.taskstage')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.shoptask')),
                ('to_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='tasks.taskstage')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
    ]
