# Generated by Django 5.2.13 on 2026-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_shoptask_external_assignee_shoptask_task_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('STAGE_MOVE', 'Stage Changed'), ('EDITED', 'Task Details Updated'), ('PHOTO_ADDED', 'Photo Added')], default='STAGE_MOVE', max_length=20),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
