# Generated by Django 5.2.13 on 2026-09-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskhistory_action_type_taskhistory_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoptask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
