# Generated by Django 5.2.13 on 2026-09-06 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_shoptask_deleted_at_shoptask_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Task Created'), ('STAGE_MOVE', 'Stage Changed'), ('EDITED', 'Task Details Updated'), ('PHOTO_ADDED', 'Photo Added'), ('COMMENT_ADDED', 'Comment Added')], default='STAGE_MOVE', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.shoptask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
