# Generated by Django 5.2.13 on 2026-04-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=20)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('financer', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('misc', models.JSONField(blank=True, default=dict, null=True)),
                ('charger', models.ForeignKey(limit_choices_to={'item_type': 'CHARGER'}, on_delete=django.db.models.deletion.PROTECT, related_name='sale_as_charger', to='inventory.stockitem')),
                ('chassis_number', models.ForeignKey(limit_choices_to={'item_type': 'SCOOTER'}, on_delete=django.db.models.deletion.PROTECT, related_name='sale_as_scooter', to='inventory.stockitem')),
                ('scooter_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.scootermodel')),
            ],
        ),
        migrations.CreateModel(
            name='SaleBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misc', models.JSONField(blank=True, default=dict, null=True)),
                ('battery', models.ForeignKey(limit_choices_to={'item_type': 'BATTERY'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockitem')),
                ('sale_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='sales.salerecord')),
            ],
        ),
    ]
