# Generated by Django 5.2.13 on 2026-10-04 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('financer', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Gross total before discounts', max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (%)', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount in Rupees', max_digits=12)),
                ('discount_reason', models.CharField(blank=True, help_text='e.g. Diwali Discount, Family and Friends Discount', max_length=200, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final bill amount', max_digits=12)),
                ('misc', models.JSONField(blank=True, default=dict, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='sale_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sale_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sales.salerecord')),
            ],
        ),
        migrations.CreateModel(
            name='SaleChargerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('sale_category', models.CharField(choices=[('WITH_SCOOTER', 'With Scooter (1st Free)'), ('WITHOUT_SCOOTER', 'Without Scooter (Standalone Retail)')], default='WITH_SCOOTER', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('charger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.charger')),
                ('sale_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charger_items', to='sales.salerecord')),
            ],
        ),
        migrations.CreateModel(
            name='SaleBatteryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('sale_category', models.CharField(choices=[('WITH_SCOOTER', 'With Scooter (Bundled Price)'), ('WITHOUT_SCOOTER', 'Without Scooter (Standalone Retail)')], default='WITH_SCOOTER', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.battery')),
                ('sale_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_items', to='sales.salerecord')),
            ],
        ),
        migrations.CreateModel(
            name='SaleScooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.CharField(max_length=100)),
                ('motor_number', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='Standard', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('configured_range_km', models.IntegerField(blank=True, help_text='Configured range with chosen battery', null=True)),
                ('configured_battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.battery')),
                ('sale_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scooter_items', to='sales.salerecord')),
                ('scooter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_scooter', to='inventory.scooter')),
                ('scooter_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.scootermodel')),
            ],
        ),
        migrations.CreateModel(
            name='SaleSparePartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('part_number', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sale_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_items', to='sales.salerecord')),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sparepart')),
            ],
        ),
    ]
