# Generated by Django 5.2.13 on 2026-05-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='sale_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sale_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sales.salerecord')),
            ],
        ),
    ]
