# Generated by Django 5.2.13 on 2026-09-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
